# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode9.3
podfile: Example/Podfile
before_install:
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/PanelController.xcworkspace -scheme PanelController-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
